Tests
wolox-training/mdr-java pull request #11
Opened 2020-03-17 19:33 UTC by martinremis

## Summary
* Add tests for controllers and models
## Trello
https://trello.com/c/szgstsc1/28-junit-testing

2020-03-18 13:50 UTC, rodrigofranc requested changes

2020-03-18 13:50 UTC, rodrigofranc commented on src/test/java/wolox/training/controllers/BookTest.java
> +  }
Use @Before for this setup

Check this https://www.baeldung.com/junit-before-beforeclass-beforeeach-beforeall

2020-03-20 14:06 UTC, rodrigofranc requested changes

2020-03-20 14:06 UTC, rodrigofranc commented on src/test/java/wolox/training/controllers/BookTest.java
> +    }
I recommend not do this, because is not a good practice do `printStackTrace()`, put the json string directly

2020-03-20 14:06 UTC, rodrigofranc commented on src/test/java/wolox/training/controllers/BookTest.java
> +@RunWith(SpringRunner.class)
`@RunWith` is not necessary in any class test

2020-03-20 14:06 UTC, rodrigofranc commented on src/test/java/wolox/training/controllers/BookTest.java
> +class BookControllerIntegrationTest {
The class name is `BookTest` but in code the name is `BookControllerIntegrationTest`. Fix this in all places

2020-03-25 14:15 UTC, rodrigofranc approved these changes

2020-03-30 14:25 UTC, rabinovichm approved these changes

2020-03-30 14:46 UTC, merged