Custom queries
wolox-training/mdr-java pull request #16
Opened 2020-03-26 14:40 UTC by martinremis

## Summary
* Change implicit repository queries for JPQL @Query
## Trello card
https://trello.com/c/6UZ3g5w0/30-queries-custom-en-repositorio

2020-03-30 12:35 UTC, rodrigofranc requested changes
Add tests when searching with all optional values in null

2020-03-30 17:37 UTC, rabinovichm requested changes
Add tests to check repositories' behaviour

2020-04-06 15:09 UTC, rabinovichm approved these changes

2020-04-06 15:55 UTC, rodrigofranc approved these changes

2020-04-06 17:40 UTC, merged