Search upgrade
wolox-training/mdr-java pull request #17
Opened 2020-03-27 14:21 UTC by martinremis

## Summary
* Upgrade search endpoints to filter by any parameter of the object (user or book)
## Trello card
https://trello.com/c/qV7UHXD0/32-filtros-en-getall-por-query-parameters

2020-03-30 18:00 UTC, rabinovichm requested changes
Add tests to the new methods in the repositories

2020-03-30 18:00 UTC, rabinovichm commented on src/main/java/wolox/training/controllers/UserController.java
> -    return userRepository.findAllByBirthdateAndName(startLocalDate,endLocalDate,partialName);
You shouldn't erase this, revive it 😄

2020-03-30 18:00 UTC, rabinovichm commented on src/main/java/wolox/training/controllers/UserController.java
> +    return userRepository.findAllWithFilters(startLocalDate,endLocalDate,name, username);
There's no need to do this according to the trello card, but if you want to, the method you should update is `readAll` and the query params should be the User Model properties (_startDate_ and _endDate_ are not needed, but `birthdate` does)

2020-03-30 18:00 UTC, rabinovichm commented on src/main/java/wolox/training/controllers/BookController.java
> +    return bookRepository.findAllWithFilters(genre, author, image, title, subtitle, publisher, year, minPages, maxPages, isbn);
beautiful, but the method you need to update is `readAll` 😋, and you shouldn't ask for min and max pages, but just for the exact amount of pages. We need to filter by the book model properties.

2020-03-30 18:00 UTC, rabinovichm commented on src/main/java/wolox/training/controllers/BookController.java
> -    return bookRepository.findAllByPublisherAndGenreAndYear(publisher, genre, year);
You shouldn't erase this, revive it 😄

2020-03-30 18:00 UTC, rabinovichm commented on src/main/java/wolox/training/repositories/BookRepository.java
> -  List<Book> findAllByPublisherAndGenreAndYear(@Param("publisher") String publisher, @Param("genre") String genre, @Param("year") String year);
Bring this back to life as it was before :zombie:

2020-03-30 18:00 UTC, rabinovichm commented on src/main/java/wolox/training/repositories/UserRepository.java
> -  Iterable<User> findAllByBirthdateAndName(
Bring this method back to life as it was before :zombie:

2020-03-30 18:00 UTC, rabinovichm commented on src/test/java/wolox/training/controllers/BookControllerIntegrationTest.java
> -        .willReturn(Arrays.asList(testBook));
**Test, come back, test!** (I hope you get the Titanic reference, if not, replace _test_ with _Jack_)

2020-03-30 18:00 UTC, rabinovichm commented on src/test/java/wolox/training/controllers/BookControllerIntegrationTest.java
> -        .willReturn(Arrays.asList(testBook));
same here

2020-03-30 18:00 UTC, rabinovichm commented on src/test/java/wolox/training/controllers/BookControllerIntegrationTest.java
> +    given(bookRepository.findAllWithFilters(
These should be two different tests

2020-03-30 18:00 UTC, rabinovichm commented on src/test/java/wolox/training/controllers/UserControllerIntegrationTest.java
> -    given(userRepository.findAllByBirthdateAndName(testUser.getBirthdate(),null,testUser.getName()))
same here

2020-03-30 18:00 UTC, rabinovichm commented on src/test/java/wolox/training/controllers/UserControllerIntegrationTest.java
> +    given(userRepository.findAllWithFilters(
Come back `findAllByBirthdateAndName`, we miss you. There should be two different tests for these two different methods.

2020-03-30 18:00 UTC, rabinovichm commented on src/test/java/wolox/training/controllers/UserControllerIntegrationTest.java
> -    given(userRepository.findAllByBirthdateAndName(testUser.getBirthdate(),testUser.getBirthdate(),testUser.getName()))
And here 😊

2020-04-01 15:16 UTC, martinremis commented on src/main/java/wolox/training/controllers/UserController.java
> -    return userRepository.findAllByBirthdateAndName(startLocalDate,endLocalDate,partialName);
Okk, I'll make a new endpoint

2020-04-01 15:23 UTC, martinremis commented on src/main/java/wolox/training/controllers/BookController.java
> +    return bookRepository.findAllWithFilters(genre, author, image, title, subtitle, publisher, year, minPages, maxPages, isbn);
I thought about it as a filter screen to search, where it would be weird to filter but an exact number of pages

2020-04-01 18:44 UTC, martinremis commented
Commits may not be really consistent with messages and previous corrections. I forgot to finish the last rebase and added new changes on the last commit of this branch :stuck_out_tongue:

2020-04-06 15:14 UTC, rabinovichm approved these changes

2020-04-06 15:56 UTC, rodrigofranc approved these changes

2020-04-06 17:41 UTC, merged