Add book repository
wolox-training/mdr-java pull request #4
Opened 2020-03-11 17:10 UTC by martinremis

## Summary
* Add Book repository

## Trello card
https://trello.com/c/vokvpwKS/15-crear-un-repositorio-de-books

2020-03-11 19:10 UTC, Mujics submitted a review, later dismissed

2020-03-11 19:14 UTC, Mujics submitted a review, later dismissed

2020-03-11 21:34 UTC, rodrigofranc requested changes

2020-03-11 21:34 UTC, rodrigofranc commented on src/main/java/wolox/training/repositories/BookRepository.java
> +  Book findFirstByAuthor(String author);
Check the Optional type, to avoid null checks in the future

2020-03-11 21:34 UTC, rodrigofranc commented on src/main/java/wolox/training/repositories/BookRepository.java
> +public interface BookRepository extends JpaRepository<Book, Id> {
All repos should extends from `CrudRepository`

2020-03-12 13:13 UTC, rodrigofranc commented on src/main/java/wolox/training/TrainingApplication.java
> +@EntityScan
I think this two are not necessary

2020-03-12 16:38 UTC, rabinovichm approved these changes
Check out [Lombok Project](https://projectlombok.org/). It's not necessary to apply it here, but it's good to know it's existence. It makes a dev's life easier :blush:

2020-03-12 18:17 UTC, rodrigofranc approved these changes

2020-03-12 18:17 UTC, merged