Add Guava PreCondition validations to setters
wolox-training/mdr-java pull request #9
Opened 2020-03-13 14:34 UTC by martinremis

## Summary
* Add Guava PreCondition validations to setters
## Trello
https://trello.com/c/lW0doehf/29-agregar-validaci%C3%B3n-de-precondiciones-a-los-setters

2020-03-13 20:51 UTC, rabinovichm requested changes
Now that you have preconditions to set object's properties, the objects' constructors should use the setters instead of assigning the values using _this.property = value_

2020-03-13 20:51 UTC, rabinovichm commented on src/main/java/wolox/training/models/Book.java
> +    this.author = Preconditions.checkNotNull(author, ErrorMessages.CANNOT_BE_NULL, "author");
The precondition should be checked before assigning the value to the object :yum:

2020-03-13 20:51 UTC, rabinovichm commented on src/main/java/wolox/training/models/Book.java
> +    this.pages = Preconditions.checkNotNull(pages, ErrorMessages.CANNOT_BE_NULL, "pages");
The number of pages should be greater than cero

2020-03-13 20:51 UTC, rabinovichm commented on src/main/java/wolox/training/models/User.java
> +    this.birthdate = Preconditions.checkNotNull(birthdate, ErrorMessages.CANNOT_BE_NULL, "birthdate");
The birthdate must be earlier than today

2020-03-16 16:48 UTC, rodrigofranc requested changes

2020-03-16 16:48 UTC, rodrigofranc commented on src/main/java/wolox/training/models/Book.java
> +    Preconditions.checkNotNull(author, StatusMessages.CANNOT_BE_NULL, "author");
Any string should be not empty

2020-03-16 16:48 UTC, rodrigofranc commented on src/main/java/wolox/training/models/Book.java
> +    Preconditions.checkNotNull(title, StatusMessages.CANNOT_BE_NULL, "title");
Any string should be not empty

2020-03-16 16:48 UTC, rodrigofranc commented on src/main/java/wolox/training/models/User.java
> +    Preconditions.checkNotNull(name, StatusMessages.CANNOT_BE_NULL, "name");
Any string should be not empty

2020-03-16 16:48 UTC, rodrigofranc commented on src/main/java/wolox/training/models/Book.java
> +    Preconditions.checkNotNull(isbn, StatusMessages.CANNOT_BE_NULL, "isbn");
Any string should be not empty

2020-03-20 17:32 UTC, rabinovichm approved these changes

2020-03-20 18:20 UTC, rodrigofranc approved these changes

2020-03-20 18:29 UTC, merged